# Site settings
title: geordee.com
email: geordee@gmail.com
description: "Personal Weblog"
baseurl: ""
url: "/"
twitter_username: "geordee"
github_username:  "geordee"

# Build settings
future: false
markdown:  kramdown
permalink: "/:year/:month/:title"
paginate:  10
plugins:
  - jekyll-paginate
